#!/usr/bin/env bash
# Taken from: https://github.com/Financial-Times/change-api/blob/c50128fc67f055356d4171f570aa2600e42dc2d1/docs/API_DEFINITION.md#script-change-logsh
PAYLOAD='{
  "systemCode": "'"$SYSTEM_CODE"'",
  "environment": "'"$RELEASE_ENV"'",
  "notifications": {
    "slackChannels": ["ft-changes-test"]
  },
  "user": {
    "email": "heroku-deploy-hook@ft.com"
  },
  "extraProperties": {
    "herokuEnv": {
      "appId": "'"$HEROKU_APP_ID"'",
      "releaseVersion": "'"$HEROKU_RELEASE_VERSION"'"
    }
  }
}'

  curl -X POST https://api.ft.com/change-log/v1/create \
-H "Content-Type: application/json" \
-H 'x-api-key: '"$CHANGE_API_KEY"'' \
-d "$PAYLOAD"