'use strict';

const sassDocExtras = require('sassdoc-extras');
const Mixin = require('./nodes/mixin');
const Function = require('./nodes/function');
const Variable = require('./nodes/variable');

class SassDoc {

    constructor(componentName, brand, doclets) {
        this.brand = brand;
        this.doclets = doclets;
        this.groupNameAliases = {
            'undefined': componentName,
        };
    }

    getNodesByKind() {
        return this.getNodes().filter(item => item.kind).reduce((nodeByKind, item) => {
            nodeByKind[item.kind] = nodeByKind[item.kind] || [];
            nodeByKind[item.kind].push(item);
            return nodeByKind;
        }, {});
    }

    /**
     * @returns {string[]} Kinds of SassDoc doclets which are supported.
     */
    static supportedDoclets() {
        return ['mixin', 'function', 'variable'];
    }

    /**
     * Format a doclet by removing superfluous properties and adding any custom properties.
     * @param {Object} doclet - A raw json doclet generated by SassDoc.
     * @returns {Object} Formatted node.
     */
    static formatDoclet(doclet) {
        switch (doclet.context.type) {
            case 'mixin':
                return new Mixin(doclet);
                break;
            case 'function':
                return new Function(doclet);
                break;
            case 'variable':
                return new Variable(doclet);
                break;
            case 'placeholder':
            default:
                throw new Error(`SassDoc type "${doclet.context.type}" is not supported by the registry.`);
                break;
        };
    }

    getNodes() {
        if (! this._formattedDoclets) {
            // Apply default values for groups and display.
            const context = {
                display: {
                    access: ['public'],
                },
                groups: this.groupNameAliases,
                data: this.doclets
            };

            // Remove any non-public doclets (configured above by the 'display' property).
            // http://sassdoc.com/extra-tools/#display-toggle-display
            sassDocExtras.display(context);
            // Customise @group names (configured above by the 'groups' above).
            // http://sassdoc.com/extra-tools/#groups-aliases-groupname
            sassDocExtras.groupName(context);
            // Remove doclet kinds the registry does not recognise or support. E.g. placeholders. 
            // These cause Origami users issues so are hidden. If used at all, placeholders should be internal to Origami only.
            // https://github.com/Financial-Times/ft-origami/issues/205
            // https://github.com/Financial-Times/ft-origami/issues/293
            context.data = context.data.filter(doclet => doclet.context && SassDoc.supportedDoclets().includes(doclet.context.type));
            // Filter out doclets that are not for the current brand.
            context.data = context.data.filter((doclet) => {
                return doclet.brand === undefined || (doclet.brand && doclet.brand.supported && doclet.brand.supported.includes(this.brand));
            });
            // Format data for registry use.
            this._formattedDoclets = context.data.map(doclet => SassDoc.formatDoclet(doclet));
        }
        return this._formattedDoclets;
    }
}

module.exports = SassDoc;
