'use strict';

const BaseNode = require('./base');

class TypedefNode extends BaseNode {
    constructor(doclet) {
        super(doclet);
        this.group = 'typedefs';
        this.label = 'Typedef';
        this.addExamples(doclet);
        this.addParameters(doclet);
        this.addReturns(doclet);
        this.addTypeDefProperties(doclet);
        this.addTypeDefTypes(doclet);
    }

    /**
     * Properties are not always their own doclet.
     * @param {Object[]} doclets - Raw json doclets generated by JSDoc.
     * @returns {Object[]} Filtered doclets.
     */
    addTypeDefProperties(doclet) {
        this.properties = this.properties || [];
        if (Array.isArray(doclet.properties)) {
            doclet.properties.forEach((property) => this.properties.push({
                'name': property.name,
                'type': property.type && property.type.names ? property.type.names : [],
                'description': this.replaceLinks(property.description) || ''
            }));
        }
    }

    addTypeDefTypes(doclet) {
        this.types = doclet.type && Array.isArray(doclet.type.names) ? doclet.type.names : [];
    }
};

module.exports = TypedefNode;
